#!/usr/bin/env python3
"""Generate SKILL_CHAPTER_MAP.md from each skill's metadata.book_chapters field.

The map is derived, not written. Running it with --check is what makes the
file's own claim ("it cannot drift") true, so CI runs that mode on every push.

    generate_chapter_map.py            # rewrite SKILL_CHAPTER_MAP.md
    generate_chapter_map.py --check    # exit 1 if the file is out of date
    generate_chapter_map.py --print    # render to stdout, touch nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "SKILL_CHAPTER_MAP.md"

CHAPTERS = {
    1: "The Process Is Your Edge",
    2: "The Financial Data Universe",
    3: "Market Microstructure",
    4: "Fundamental and Alternative Data",
    5: "Synthetic Financial Data",
    6: "Strategy Research Framework",
    7: "Defining the Learning Task",
    8: "Financial Feature Engineering",
    9: "Model-Based Feature Extraction",
    10: "Text Feature Engineering",
    11: "The ML Pipeline",
    12: "Advanced Models for Tabular Data",
    13: "Deep Learning for Time Series",
    14: "Latent Factor Models",
    15: "Causal Machine Learning",
    16: "Strategy Simulation",
    17: "Portfolio Construction",
    18: "Transaction Costs",
    19: "Risk Management",
    20: "Strategy Synthesis",
    21: "Reinforcement Learning for Execution and Hedging",
    22: "RAG for Financial Research",
    23: "Knowledge Graphs",
    24: "Autonomous Agents",
    25: "Live Trading Systems",
    26: "MLOps and Governance",
    27: "The Systematic Edge",
}

# Directory name -> display name, in the order the README lists them.
CATEGORIES = {
    "concepts": "Concepts",
    "data": "Data",
    "features": "Features",
    "validation": "Validation",
    "backtest": "Backtest",
    "portfolio": "Portfolio",
    "advanced-ai": "Advanced AI",
    "production": "Production",
    "infrastructure": "Infrastructure",
    "workflows": "Workflows",
}

HEADER = """# Skill Chapter Map

Every skill in this repository maps to the chapter of *Machine Learning for
Algorithmic Trading, 3rd Edition* that develops the method in full. This file is
generated by `scripts/generate_chapter_map.py` from each skill's
`metadata.book_chapters` field, and CI fails if it is out of date, so it cannot
drift from the skills themselves.
"""

FOOTER = """The chapters listed above with no skill develop methods whose failure modes are
either well covered by general ML practice or not yet reduced to a procedure
worth writing down, apart from the closing synthesis chapter, which has no
method of its own. These are gaps in the collection, recorded here rather than
hidden.
"""


def chapters_of(skill: Path) -> list[int]:
    frontmatter = skill.read_text(encoding="utf-8").split("---", 2)[1]
    match = re.search(r'^\s*book_chapters:\s*"?([^"\n]*)"?', frontmatter, re.MULTILINE)
    if not match:
        raise SystemExit(f"{skill}: no metadata.book_chapters")
    numbers = []
    for part in match.group(1).split(","):
        part = part.strip()
        if not part:
            continue
        if not part.isdigit() or int(part) not in CHAPTERS:
            raise SystemExit(f"{skill}: invalid book chapter {part!r}")
        numbers.append(int(part))
    if not numbers:
        raise SystemExit(f"{skill}: empty metadata.book_chapters")
    return sorted(numbers)


def collect() -> dict[str, list[tuple[str, Path, list[int]]]]:
    by_category: dict[str, list[tuple[str, Path, list[int]]]] = {key: [] for key in CATEGORIES}
    for category in CATEGORIES:
        for skill in sorted((ROOT / category).glob("*/SKILL.md")):
            by_category[category].append((skill.parent.name, skill, chapters_of(skill)))
    unknown = [d.name for d in ROOT.iterdir() if d.is_dir() and list(d.glob("*/SKILL.md"))]
    for name in unknown:
        if name not in CATEGORIES:
            raise SystemExit(f"category {name!r} holds skills but is not in CATEGORIES")
    return by_category


def render(by_category: dict[str, list[tuple[str, Path, list[int]]]]) -> str:
    total = sum(len(v) for v in by_category.values())
    out = [HEADER, f"Generated from {total} skills against the "
           f"{len(CHAPTERS)}-chapter outline.", "", "## By skill", ""]

    for category, display in CATEGORIES.items():
        entries = by_category[category]
        out += [f"### {display} ({len(entries)})", "", "| Skill | Chapters |", "|---|---|"]
        for name, _, numbers in entries:
            listed = "; ".join(f"{n} {CHAPTERS[n]}" for n in numbers)
            out.append(f"| [`ml4t-{name}`]({category}/{name}/) | {listed} |")
        out.append("")

    out += ["## By chapter", "", "| Chapter | Skills |", "|---|---|"]
    for number, title in CHAPTERS.items():
        names = sorted(
            f"`ml4t-{name}`"
            for entries in by_category.values()
            for name, _, numbers in entries
            if number in numbers
        )
        out.append(f"| **{number}** {title} | {', '.join(names) if names else 'none'} |")
    out.append("")

    unmapped = [
        n
        for n in CHAPTERS
        if not any(n in numbers for entries in by_category.values() for _, _, numbers in entries)
    ]
    out += ["## Chapters with no mapped skill", ""]
    if unmapped:
        listed = ", ".join(f"{n} ({CHAPTERS[n]})" for n in unmapped)
        out += [f"{len(unmapped)} of {len(CHAPTERS)} chapters have no skill pointing at "
                f"them: {listed}.", "", FOOTER]
    else:
        out += ["Every chapter has at least one skill pointing at it.", ""]
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is out of date")
    parser.add_argument("--print", dest="show", action="store_true", help="render to stdout only")
    args = parser.parse_args()

    rendered = render(collect())

    if args.show:
        print(rendered, end="")
        return 0

    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current == rendered:
        print(f"{OUTPUT.name} is current")
        return 0
    if args.check:
        print(
            f"{OUTPUT.name} is out of date; run scripts/generate_chapter_map.py",
            file=sys.stderr,
        )
        return 1

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"{OUTPUT.name} regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
